// Gerado: cada emoji do app → um ícone desenhado (Phosphor). O que não está aqui continua como emoji.
import {
  Airplane,
  Alarm,
  AppleLogo,
  ArrowDown,
  ArrowUUpLeft,
  ArrowUp,
  Baby,
  Backpack,
  Bank,
  Barbell,
  Basket,
  Bed,
  BeerStein,
  Bell,
  Bicycle,
  Bone,
  Books,
  BowlFood,
  BowlSteam,
  Brain,
  Bread,
  Briefcase,
  Broom,
  Buildings,
  Bus,
  Cake,
  Calendar,
  CalendarBlank,
  Camera,
  Car,
  Carrot,
  Cat,
  ChartBar,
  CheckCircle,
  Cheese,
  ClipboardText,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Confetti,
  Cookie,
  Couch,
  Cow,
  CreditCard,
  Cube,
  DeviceMobile,
  DeviceMobileCamera,
  Diamond,
  Dog,
  DownloadSimple,
  Dress,
  Drop,
  Egg,
  Envelope,
  Eye,
  FileText,
  FilmSlate,
  FilmStrip,
  Fire,
  Flask,
  FloppyDisk,
  Flower,
  FlowerTulip,
  FolderOpen,
  ForkKnife,
  GameController,
  GasPump,
  Gear,
  Gift,
  Globe,
  GlobeHemisphereWest,
  GraduationCap,
  Grains,
  Guitar,
  Hamburger,
  HandHeart,
  HandSoap,
  Handshake,
  Headphones,
  Heart,
  Hospital,
  Hourglass,
  House,
  HouseLine,
  Jar,
  Jeep,
  Key,
  Laptop,
  Leaf,
  LetterCircleP,
  Lifebuoy,
  Lightbulb,
  Lightning,
  Link,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Microphone,
  Minus,
  Money,
  MoneyWavy,
  Moon,
  Motorcycle,
  MusicNote,
  Note,
  Package,
  Palette,
  PawPrint,
  PencilSimple,
  PersonSimpleRun,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plant,
  Play,
  Plug,
  Plus,
  Popcorn,
  Printer,
  PushPin,
  Receipt,
  Repeat,
  Robot,
  RocketLaunch,
  Scales,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Shower,
  Shuffle,
  Sneaker,
  Sparkle,
  Star,
  Stethoscope,
  Student,
  Sun,
  Tag,
  Target,
  Taxi,
  Television,
  Ticket,
  Timer,
  Toilet,
  Toolbox,
  Tooth,
  Train,
  Trash,
  TreeEvergreen,
  TrendUp,
  Trophy,
  Umbrella,
  User,
  Warning,
  WaveSine,
  WifiHigh,
  Wind,
  Wrench,
  type Icon,
} from "@phosphor-icons/react";

export const ICONES: Record<string, Icon> = {
  "💳": CreditCard,
  "🏦": Bank,
  "⚠️": Warning,
  "🔁": Repeat,
  "🛒": ShoppingCart,
  "📌": PushPin,
  "💡": Lightbulb,
  "✨": Sparkle,
  "🍽️": ForkKnife,
  "🎯": Target,
  "🎉": Confetti,
  "🏷️": Tag,
  "🏠": House,
  "📺": Television,
  "🚗": Car,
  "✏️": PencilSimple,
  "🛍️": ShoppingBag,
  "🔗": Link,
  "🛟": Lifebuoy,
  "💼": Briefcase,
  "🎓": GraduationCap,
  "💰": Coins,
  "🧾": Receipt,
  "🧴": Drop,
  "💻": Laptop,
  "📅": CalendarBlank,
  "🌸": Flower,
  "💚": Heart,
  "💵": Money,
  "💸": MoneyWavy,
  "⛽": GasPump,
  "📱": DeviceMobile,
  "⏳": Hourglass,
  "☁️": Cloud,
  "⚖️": Scales,
  "⏰": Alarm,
  "📋": ClipboardText,
  "🧭": Compass,
  "🎁": Gift,
  "🏆": Trophy,
  "📸": Camera,
  "📥": DownloadSimple,
  "🎟️": Ticket,
  "📈": TrendUp,
  "🔥": Fire,
  "🚀": RocketLaunch,
  "🏡": HouseLine,
  "🚌": Bus,
  "📦": Package,
  "🎮": GameController,
  "🐶": Dog,
  "🤝": Handshake,
  "🌙": Moon,
  "💜": Heart,
  "⭐": Star,
  "🗺️": MapTrifold,
  "⬆️": ArrowUp,
  "🧹": Broom,
  "🍝": BowlFood,
  "🎤": Microphone,
  "➕": Plus,
  "📄": FileText,
  "📂": FolderOpen,
  "〰️": WaveSine,
  "🔍": MagnifyingGlass,
  "☀️": Sun,
  "💪": Barbell,
  "🎄": TreeEvergreen,
  "🎬": FilmSlate,
  "📚": Books,
  "✈️": Airplane,
  "💍": Diamond,
  "🥩": Cow,
  "🥤": Coffee,
  "🧽": Sparkle,
  "🪥": Tooth,
  "🩺": Stethoscope,
  "🌱": Plant,
  "🧓": User,
  "👤": User,
  "🎨": Palette,
  "🔔": Bell,
  "💾": FloppyDisk,
  "⬇️": ArrowDown,
  "🔑": Key,
  "↩️": ArrowUUpLeft,
  "📬": Envelope,
  "🔐": Lock,
  "📊": ChartBar,
  "🔮": Sparkle,
  "🖨️": Printer,
  "👗": Dress,
  "👟": Sneaker,
  "➖": Minus,
  "⚙️": Gear,
  "🔎": MagnifyingGlass,
  "🗓️": Calendar,
  "📲": DeviceMobileCamera,
  "📍": MapPin,
  "✅": CheckCircle,
  "🏍": Motorcycle,
  "🚙": Jeep,
  "🏖️": Umbrella,
  "🍔": Hamburger,
  "💊": Pill,
  "🐷": PiggyBank,
  "🔓": LockOpen,
  "🏍️": Motorcycle,
  "🛠️": Wrench,
  "🛋️": Couch,
  "🌍": GlobeHemisphereWest,
  "🎸": Guitar,
  "⏱️": Timer,
  "🧰": Toolbox,
  "🔀": Shuffle,
  "🥫": Jar,
  "🥦": Carrot,
  "🧀": Cheese,
  "🐾": PawPrint,
  "🍚": BowlSteam,
  "🫘": Grains,
  "☕": Coffee,
  "🍬": Cookie,
  "🫒": Leaf,
  "🧂": Jar,
  "🥚": Egg,
  "🍞": Bread,
  "🧈": Cube,
  "🍎": AppleLogo,
  "💧": Drop,
  "🧺": Basket,
  "🧪": Flask,
  "🫧": Drop,
  "🗑️": Trash,
  "🧻": Toilet,
  "🧼": HandSoap,
  "🌬️": Wind,
  "🩷": Heart,
  "🦷": Tooth,
  "💆": Flower,
  "👁️": Eye,
  "🌹": FlowerTulip,
  "🐱": Cat,
  "🦴": Bone,
  "🏢": Buildings,
  "🚿": Shower,
  "📶": WifiHigh,
  "🎧": Headphones,
  "🎞️": FilmStrip,
  "▶️": Play,
  "🤖": Robot,
  "🏋️": Barbell,
  "🧠": Brain,
  "🚕": Taxi,
  "🅿️": LetterCircleP,
  "🤲": HandHeart,
  "🍿": Popcorn,
  "🎵": MusicNote,
  "🏥": Hospital,
  "🐕": Dog,
  "🧸": Baby,
  "👶": Baby,
  "💇": Scissors,
  "🎂": Cake,
  "🍕": Pizza,
  "🍺": BeerStein,
  "🛏️": Bed,
  "🔌": Plug,
  "📞": Phone,
  "🏫": Student,
  "📝": Note,
  "🔧": Wrench,
  "🚲": Bicycle,
  "🚇": Train,
  "⚡": Lightning,
  "🌐": Globe,
  "📦️": Package,
  "🎒": Backpack,
  "🏃": PersonSimpleRun,
};
